// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDPf-Qo95Nm2qNT9JoPi1Bx46EfpqVjk',
    appId: '1:21607265647:web:785485453f077b7c81e49a',
    messagingSenderId: '21607265647',
    projectId: 'mini-project-19b69',
    authDomain: 'mini-project-19b69.firebaseapp.com',
    storageBucket: 'mini-project-19b69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgdbUtUtcEAeQ2UaoiSN1rMzjDcOPrkk',
    appId: '1:21607265647:android:27d9c8f4c145498781e49a',
    messagingSenderId: '21607265647',
    projectId: 'mini-project-19b69',
    storageBucket: 'mini-project-19b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3w4b6jJaFZRr-H8_ZuKBPppHYN46n-Tg',
    appId: '1:21607265647:ios:224748a3e270bd7a81e49a',
    messagingSenderId: '21607265647',
    projectId: 'mini-project-19b69',
    storageBucket: 'mini-project-19b69.appspot.com',
    iosClientId: '21607265647-mndek2i8mib5ir2kpj8jhi3a973qeor1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventnoti',
  );
}
